### ISSUE TITLE
Policy Struct changed

### ISSUE THREAD

**Issue by kstedman9** [nemosupremo/vault-gatekeeper#68]
We have been using Vault-Gatekeeper for several years now and I was surprised when I pulled the latest source code to see a change to the policy data struct.  It looks like 3 months ago a change was checked in that changed the struct of the policy.  In vault we now have to wrap the vault data with another data.

{ "data": { "data": [{"*": { "policies":["default"], "num_uses": 0}]}}

I see the code change in the policy.go file line 173.

**Comment by nemosupremo** [comment]
A couple months ago Vault Gatekeeper was changed to 1.0 (from 0.x), which had a number of breaking changes. With regards to the policies, the biggest change is Gatekeeper now uses [AppRoles](https://www.vaultproject.io/docs/auth/approle.html) instead of creating tokens directly. The `policies` key is no longer used in favor of the `roles` key.

The [Getting Started](http://nemosupremo.github.io/vault-gatekeeper/docs/doc.html#getting-started) doc describes how to configure gatekeeper.

Admittedly I can't understand your issue and why you have to do wrapping now.

**Comment by kstedman9** [comment]
Yeah I have noticed that.  It took me a while and some reading of the code to realize the new structure.  I understand more why you have the extra "data" json object in there now. 

Unfortunately, I had to add a bunch of debugging to the code to figure out what was going on with the new configs.  Was trying to convert my old ones to the new style.   We used a lot of "*" in the old configs instead of specifying every task under a folder which it looks like you no longer support.

I will be providing a pull request soon.  I fixed the gatekeeper client code which has the /token response incorrect in it.  I also added a new scheduler for DCOS Enterprise Edition Strict mode.   In that scheduler I also changed how the mesos calls were made.  In the mesos scheduler, you have it making one call /state.json.  On our operational cluster this takes too long to pull and parse (Even DCOS has issues with this) so we have to change timeout settings.   We have several hundred-thousand plus active tasks at any one time that are constantly changing (tons of very short running tasks).
